name: alarm_clock
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  load_switch: ^2.1.0
  flutter_svg: ^2.0.10+1
  wheel_picker: ^0.1.1
  timelines: ^0.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  alarm: ^4.0.8
  intl: ^0.19.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/audio1.mp3

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Medium.ttf
